"""Add trial_used and updated_at to Users

Revision ID: 4e3ca7823358
Revises: ec1b1abfc28a
Create Date: 2025-05-28 00:51:44.291005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e3ca7823358'
down_revision: Union[str, None] = 'ec1b1abfc28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_entries')
    op.drop_table('anime')
    op.drop_index('unique_constraint', table_name='fingerprints')
    op.drop_table('fingerprints')
    op.drop_index('_playlist_song_uc', table_name='playlist_songs')
    op.drop_index('ix_playlist_songs_id', table_name='playlist_songs')
    op.drop_table('playlist_songs')
    op.drop_table('users')
    op.drop_index('song_id', table_name='songs')
    op.drop_index('song_name', table_name='songs')
    op.drop_table('songs')
    op.drop_table('playlists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('theme', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('name_tags', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='playlists_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('songs',
    sa.Column('song_id', mysql.MEDIUMINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('song_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fingerprinted', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('artist', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('streaming_service', mysql.VARCHAR(length=254), nullable=True),
    sa.Column('cover_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('audio_url', mysql.TEXT(), nullable=True),
    sa.Column('duration', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('file_sha1', sa.BINARY(length=20), nullable=False),
    sa.Column('op_ed_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('anime_title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('season', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fandom_tags', mysql.TEXT(), nullable=True),
    sa.Column('song_duration', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('genres', mysql.TEXT(), nullable=True),
    sa.Column('tags', mysql.TEXT(), nullable=True),
    sa.Column('youtube_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('spotify_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('video_url', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('song_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('song_name', 'songs', ['song_name'], unique=True)
    op.create_index('song_id', 'songs', ['song_id'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_pw', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_subscribed', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('subscription_expires', mysql.DATETIME(), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('stripe_customer_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stripe_subscription_id', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('playlist_songs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('song_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('audio_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('duration', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='playlist_songs_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_playlist_songs_id', 'playlist_songs', ['id'], unique=False)
    op.create_index('_playlist_song_uc', 'playlist_songs', ['playlist_id', 'song_name'], unique=True)
    op.create_table('fingerprints',
    sa.Column('hash', sa.BINARY(length=10), nullable=False),
    sa.Column('song_id', mysql.MEDIUMINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('offset', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], name='fingerprints_ibfk_1', ondelete='CASCADE'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_constraint', 'fingerprints', ['song_id', 'offset', 'hash'], unique=True)
    op.create_table('anime',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_romaji', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title_english', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title_native', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('cover_image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('season', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('season_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('format', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('genres', mysql.TEXT(), nullable=True),
    sa.Column('tags', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('playlist_entries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('song_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('duration', mysql.FLOAT(), nullable=False),
    sa.Column('added_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('audio_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='playlist_entries_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
