"""initial schema

Revision ID: b4bbc316bf0c
Revises: c2089d327f43
Create Date: 2025-07-16 01:30:04.140693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4bbc316bf0c'
down_revision: Union[str, None] = 'c2089d327f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'cover_image',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('anime', 'season',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('anime', 'format',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_anime_title_romaji'), 'anime', ['title_romaji'], unique=True)
    op.drop_column('anime', 'genres')
    op.drop_column('anime', 'title_native')
    op.drop_column('anime', 'tags')
    op.alter_column('genre', 'name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.drop_index('ix_genre_id', table_name='genre')
    op.alter_column('log', 'api_key',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('log', 'search_type',
               existing_type=mysql.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('log', 'song_id',
               existing_type=mysql.MEDIUMINT(display_width=8, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_log_api_key'), 'log', ['api_key'], unique=False)
    op.create_index(op.f('ix_log_id'), 'log', ['id'], unique=False)
    op.drop_constraint('password_reset_tokens_ibfk_1', 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_playlist_entries_playlist', table_name='playlist_entries')
    op.create_unique_constraint('_playlist_entries_uc', 'playlist_entries', ['playlist_id', 'song_name'])
    op.create_index(op.f('ix_playlist_entries_id'), 'playlist_entries', ['id'], unique=False)
    op.create_index(op.f('ix_playlist_entries_playlist_id'), 'playlist_entries', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_entries_song_name'), 'playlist_entries', ['song_name'], unique=False)
    op.drop_column('playlist_entries', 'added_at')
    op.add_column('playlists', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('playlists', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('playlists', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('playlists', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('playlists_ibfk_1', 'playlists', type_='foreignkey')
    op.create_foreign_key(None, 'playlists', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('playlists', 'theme')
    op.drop_column('playlists', 'name_tags')
    op.drop_column('playlists', 'description')
    op.add_column('songs', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('songs', 'song_id',
               existing_type=mysql.MEDIUMINT(display_width=8, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('songs', 'artist',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               nullable=False)
    op.create_index(op.f('ix_songs_artist'), 'songs', ['artist'], unique=False)
    op.create_index(op.f('ix_songs_song_id'), 'songs', ['song_id'], unique=False)
    op.drop_column('songs', 'name')
    op.drop_column('songs', 'anime_title')
    op.drop_column('songs', 'song_duration')
    op.drop_column('songs', 'genres')
    op.drop_column('songs', 'video_url')
    op.drop_column('songs', 'fingerprinted')
    op.drop_column('songs', 'file_sha1')
    op.drop_column('songs', 'fandom_tags')
    op.drop_column('songs', 'spotify_url')
    op.drop_column('songs', 'tags')
    op.drop_column('songs', 'audio_url')
    op.drop_column('songs', 'song_name')
    op.drop_column('songs', 'duration')
    op.drop_column('songs', 'cover_url')
    op.drop_column('songs', 'op_ed_type')
    op.drop_column('songs', 'youtube_url')
    op.drop_column('songs', 'season')
    op.drop_column('songs', 'streaming_service')
    op.alter_column('user', 'api_key',
               existing_type=mysql.VARCHAR(length=128),
               server_default=None,
               nullable=False)
    op.alter_column('user', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'provider_uid',
               existing_type=mysql.VARCHAR(length=191),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               nullable=True)
    op.alter_column('user', 'verification_token',
               existing_type=mysql.VARCHAR(length=191),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('user', 'display_name',
               existing_type=mysql.VARCHAR(length=191),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('user', 'is_subscribed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'stripe_customer_id',
               existing_type=mysql.VARCHAR(length=191),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('user', 'stripe_subscription_id',
               existing_type=mysql.VARCHAR(length=191),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('user', 'email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'trial_used',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('api_key_2', table_name='user')
    op.drop_index('provider_uid', table_name='user')
    op.drop_index('user_id', table_name='user')
    op.drop_index('user_id_2', table_name='user')
    op.create_index(op.f('ix_user_api_key'), 'user', ['api_key'], unique=True)
    op.create_index(op.f('ix_user_display_name'), 'user', ['display_name'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_provider_uid'), 'user', ['provider_uid'], unique=True)
    op.create_index('uq_user_display_name_lower', 'user', [sa.text('lower(display_name)')], unique=False)
    op.create_unique_constraint(None, 'user', ['stripe_subscription_id'])
    op.create_unique_constraint(None, 'user', ['stripe_customer_id'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'notes')
    op.drop_column('user', 'tier')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', mysql.VARCHAR(length=191), nullable=True))
    op.add_column('user', sa.Column('tier', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('notes', mysql.TEXT(), nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'tier', ['tier'], ['id'])
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index('uq_user_display_name_lower', table_name='user')
    op.drop_index(op.f('ix_user_provider_uid'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_display_name'), table_name='user')
    op.drop_index(op.f('ix_user_api_key'), table_name='user')
    op.create_index('user_id_2', 'user', ['id'], unique=True)
    op.create_index('user_id', 'user', ['id'], unique=False)
    op.create_index('provider_uid', 'user', ['provider_uid'], unique=True)
    op.create_index('api_key_2', 'user', ['api_key'], unique=True)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'),
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('current_timestamp()'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('user', 'trial_used',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('user', 'email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('user', 'stripe_subscription_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=True)
    op.alter_column('user', 'stripe_customer_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=True)
    op.alter_column('user', 'is_subscribed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('user', 'display_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=False)
    op.alter_column('user', 'verification_token',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=True)
    op.alter_column('user', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=256),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=256),
               existing_nullable=False)
    op.alter_column('user', 'provider_uid',
               existing_type=mysql.VARCHAR(length=191),
               nullable=True)
    op.alter_column('user', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('user', 'api_key',
               existing_type=mysql.VARCHAR(length=128),
               server_default=sa.text("''"),
               nullable=True)
    op.add_column('songs', sa.Column('streaming_service', mysql.VARCHAR(length=254), nullable=True))
    op.add_column('songs', sa.Column('season', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('songs', sa.Column('youtube_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('songs', sa.Column('op_ed_type', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('songs', sa.Column('cover_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('songs', sa.Column('duration', mysql.FLOAT(), server_default=sa.text('0'), nullable=True))
    op.add_column('songs', sa.Column('song_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('songs', sa.Column('audio_url', mysql.TEXT(), nullable=True))
    op.add_column('songs', sa.Column('tags', mysql.TEXT(), nullable=True))
    op.add_column('songs', sa.Column('spotify_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('songs', sa.Column('fandom_tags', mysql.TEXT(), nullable=True))
    op.add_column('songs', sa.Column('file_sha1', sa.BINARY(length=20), nullable=False))
    op.add_column('songs', sa.Column('fingerprinted', mysql.TINYINT(display_width=4), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('video_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('songs', sa.Column('genres', mysql.TEXT(), nullable=True))
    op.add_column('songs', sa.Column('song_duration', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('anime_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('songs', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_songs_song_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_artist'), table_name='songs')
    op.alter_column('songs', 'artist',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('songs', 'song_id',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(display_width=8, unsigned=True),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('songs', 'title')
    op.add_column('playlists', sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column('playlists', sa.Column('name_tags', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('playlists', sa.Column('theme', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.create_foreign_key('playlists_ibfk_1', 'playlists', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('playlists', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('current_timestamp()'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('playlists', 'name',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('playlists', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('playlists', 'updated_at')
    op.add_column('playlist_entries', sa.Column('added_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True))
    op.drop_index(op.f('ix_playlist_entries_song_name'), table_name='playlist_entries')
    op.drop_index(op.f('ix_playlist_entries_playlist_id'), table_name='playlist_entries')
    op.drop_index(op.f('ix_playlist_entries_id'), table_name='playlist_entries')
    op.drop_constraint('_playlist_entries_uc', 'playlist_entries', type_='unique')
    op.create_index('idx_playlist_entries_playlist', 'playlist_entries', ['playlist_id'], unique=False)
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key('password_reset_tokens_ibfk_1', 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_log_id'), table_name='log')
    op.drop_index(op.f('ix_log_api_key'), table_name='log')
    op.alter_column('log', 'song_id',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(display_width=8, unsigned=True),
               existing_nullable=True)
    op.alter_column('log', 'search_type',
               existing_type=mysql.VARCHAR(length=10),
               server_default=sa.text("'scene'"),
               existing_nullable=False)
    op.alter_column('log', 'api_key',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.create_index('ix_genre_id', 'genre', ['id'], unique=False)
    op.alter_column('genre', 'name',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.add_column('anime', sa.Column('tags', mysql.TEXT(), nullable=True))
    op.add_column('anime', sa.Column('title_native', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('anime', sa.Column('genres', mysql.TEXT(), nullable=True))
    op.drop_index(op.f('ix_anime_title_romaji'), table_name='anime')
    op.alter_column('anime', 'format',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('anime', 'season',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('anime', 'cover_image',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
